### ISSUE TITLE
Error Unhabdled Promise

### ISSUE THREAD

**Issue by subhrawdc** [docusign/eg-01-node-jwt#2]
Get the below error. 

````
(node:20667) UnhandledPromiseRejectionWarning: Error: error:0906D06C:PEM routines:PEM_read_bio:no start line
    at Sign.sign (crypto.js:331:26)
    at Object.sign (/var/www/html/node-jwt-master/node_modules/jwa/index.js:76:45)
    at Object.jwsSign [as sign] (/var/www/html/node-jwt-master/node_modules/jws/lib/sign-stream.js:32:24)
    at Object.module.exports [as sign] (/var/www/html/node-jwt-master/node_modules/jsonwebtoken/sign.js:189:16)
    at exports.configureJWTAuthorizationFlow (/var/www/html/node-jwt-master/node_modules/docusign-esign/src/ApiClient.js:602:25)
    at exports.<anonymous> (internal/util.js:230:26)
    at _DS_JWT_Auth.__getToken [as _getToken] (/var/www/html/node-jwt-master/lib/DS_JWT_Auth.js:112:5)
    at _DS_JWT_Auth._checkToken [as checkToken] (/var/www/html/node-jwt-master/lib/DS_JWT_Auth.js:82:16)
    at _SendEnvelope._sendEnvelope1 [as sendEnvelope1] (/var/www/html/node-jwt-master/lib/SendEnvelope.js:56:25)
    at _main (/var/www/html/node-jwt-master/index.js:48:36)
    at main (/var/www/html/node-jwt-master/index.js:73:11)
    at Object.<anonymous> (/var/www/html/node-jwt-master/index.js:105:1)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:191:16)
    at bootstrap_node.js:612:3
(node:20667) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:20667) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
````

Can you help?

**Comment by LarryKlugerDS** [comment]
I'm sorry for the long delay in this reply. We've re-organized to help speedup replies.

The error message shows the problem at the very beginning:

> (node:20667) UnhandledPromiseRejectionWarning: Error: error:0906D06C:PEM routines:PEM_read_bio:no start line

--The problem was that you didn't include the start line for the private key when you added it to the dsConfig file.
